// Custom frequency generator sample file generated by iCEcube2

// Frequency formula for SIMPLE feedback mode
// FOUT = FREF * (DIVF + 1)
//        -------------------
//        2^DIVQ * (DIVR + 1)

// DIVR - 16 bit
// DIVF - 64 bit
// DIVQ - 8 bit

module custompllclock(REFERENCECLK,
                      PLLOUTCORE,
                      PLLOUTGLOBAL,
                      RESET);

	input REFERENCECLK;
	input RESET;    /* To initialize the simulation properly, the RESET signal (Active Low) must be asserted at the beginning of the simulation */ 
	output PLLOUTCORE;
	output PLLOUTGLOBAL;

	SB_PLL40_CORE custompllclock_inst(.REFERENCECLK(REFERENCECLK),
	                                  .PLLOUTCORE(PLLOUTCORE),
	                                  .PLLOUTGLOBAL(PLLOUTGLOBAL),
	                                  .EXTFEEDBACK(),
	                                  .DYNAMICDELAY(),
	                                  .RESETB(RESET),
	                                  .BYPASS(1'b0),
	                                  .LATCHINPUTVALUE(),
	                                  .LOCK(),
	                                  .SDI(),
	                                  .SDO(),
	                                  .SCLK());

	// Fin=48, Fout=16;
	defparam custompllclock_inst.DIVR = 4'b0010;
	defparam custompllclock_inst.DIVF = 7'b0111111;
	defparam custompllclock_inst.DIVQ = 3'b110;
	defparam custompllclock_inst.FILTER_RANGE = 3'b001;
	defparam custompllclock_inst.FEEDBACK_PATH = "SIMPLE";
	defparam custompllclock_inst.DELAY_ADJUSTMENT_MODE_FEEDBACK = "FIXED";
	defparam custompllclock_inst.FDA_FEEDBACK = 4'b0000;
	defparam custompllclock_inst.DELAY_ADJUSTMENT_MODE_RELATIVE = "FIXED";
	defparam custompllclock_inst.FDA_RELATIVE = 4'b0000;
	defparam custompllclock_inst.SHIFTREG_DIV_MODE = 2'b00;
	defparam custompllclock_inst.PLLOUT_SELECT = "GENCLK";
	defparam custompllclock_inst.ENABLE_ICEGATE = 1'b0;
endmodule
